ALTER TABLE recibos ADD COLUMN estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE';

-- MySQL: para quitar NOT NULL se usa MODIFY COLUMN (equivalente a ALTER COLUMN DROP NOT NULL en PostgreSQL)
ALTER TABLE recibos MODIFY COLUMN metodo_pago VARCHAR(50) NULL;
